name: cythonize_mvp_lite_package

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest

    permissions:
      contents: write

    env:
      src_dir_path: "./mvp_lite_root/src/mvp_lite"
      package_name: "mvp_lite"
      cythonized_folder_name: "compiled_package"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Cython
        run: pip install cython

      - name: Cythonize package
        run: |
          python ./cythonization_git_script/cythonize_py_files.py `
            "${{ env.src_dir_path }}" `
            "${{ env.package_name }}" `
            "${{ env.cythonized_folder_name }}"

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "MVP Lite package cythonized"
          git push origin main